- name: add kvm container hosts
  add_host:
    hostname: "{{ item.value.ip }}"
    groupname: container_hosts
    ansible_ssh_pass: "{{ provider_config.kvm.root_pwd }}"
  when: item.value.provider=='kvm'
  with_dict: "{{ instances }}"
  tags:
    - configure_kvm_instances
    - install_contrail

- name: add gce container hosts
  include: add_gce_container_hosts.yml
  when: item.value.provider=='gce'
  with_dict: "{{ instances }}"
  tags:
    - configure_gce_instances
    - install_contrail
