- name: Create container host group
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
  - create_container_host_group
  vars_files:
    - "{{ vars_dir }}/instances.yml"
    - "{{ vars_dir }}/accounts.yml"

- name: Configure instance(s)
  hosts: container_hosts
  gather_facts: yes
  roles:
  - configure_instances
  vars_files:
    - "{{ vars_dir }}/instances.yml"
    - "{{ vars_dir }}/accounts.yml"
