- name: Create container host group
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
  - create_container_host_group
  vars_files:
    - "{{ config_dir }}/instances.yml"
    - "{{ config_dir }}/accounts.yml"
  tags:
  - install_contrail

- name: Install Contrail
  hosts: container_hosts
  gather_facts: yes
  roles:
  - install_contrail
  vars_files:
  - "{{ hostvars['localhost'].config_dir }}/instances.yml"
  - "{{ hostvars['localhost'].config_dir }}/accounts.yml"
  tags:
  - install_contrail

