- name: Create GCE instance(s)
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
  - create_gce_instances
  vars_files:
  - "{{ config_dir }}/instances"
#  - "{{ config_dir }}/instances.yml"
#  - "{{ config_dir }}/accounts.yml"
  tags:
  - create_gce_instances

- name: Get KVM instances
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
  - get_kvm_instances
  vars_files:
  - "{{ config_dir }}/instances"
#  - "{{ config_dir }}/instances.yml"
#  - "{{ config_dir }}/accounts.yml"
  tags:
  - create_kvm_instances

- name: Create KVM instances
  hosts: kvm_instances
  roles:
  - create_kvm_instances
  vars_files:
  - "{{ hostvars['localhost'].config_dir }}/instances"
#  - "{{ hostvars['localhost'].config_dir }}/instances.yml"
#  - "{{ hostvars['localhost'].config_dir }}/accounts.yml"
  tags:
  - create_kvm_instances
